--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from telco_customers3
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from telco_customers3 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from telco_customers3)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from telco_customers3
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from telco_customers3
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM telco_customers3
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM telco_customers3
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM telco_customers3)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM telco_customers3
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM telco_customers3
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM telco_customers3
GROUP BY age_group
ORDER BY total_revenue desc;



CREATE INDEX IF NOT EXISTS idx_telco_customers2_location      ON telco_customers3 (location);
CREATE INDEX IF NOT EXISTS idx_telco_customers2_category      ON telco_customers3 (category);
CREATE INDEX IF NOT EXISTS idx_telco_customers2_segment       ON telco_customers3 (segment);
CREATE INDEX IF NOT EXISTS idx_telco_customers2_item          ON telco_customers3 (item_purchased);
CREATE INDEX IF NOT EXISTS idx_telco_customers2_payment       ON telco_customers3 (payment_method);
CREATE INDEX IF NOT EXISTS idx_telco_customers2_transaction  ON telco_customers3 (customer_id);  


-- 2) Dimension / Lookup tables 

DROP TABLE IF EXISTS dim_category;
CREATE TABLE dim_category AS
SELECT DISTINCT COALESCE(category, 'Unknown') AS category_name
FROM telco_customers3
ORDER BY 1;

DROP TABLE IF EXISTS dim_payment_method;
CREATE TABLE dim_payment_method AS
SELECT DISTINCT COALESCE(payment_method, 'Unknown') AS payment_name
FROM telco_customers3
ORDER BY 1;

DROP TABLE IF EXISTS dim_location;
CREATE TABLE dim_location AS
SELECT DISTINCT COALESCE(location, 'Unknown') AS location_name
FROM telco_customers3
ORDER BY 1;


DROP TABLE IF EXISTS dim_segment;
CREATE TABLE dim_segment AS
SELECT DISTINCT segment AS segment_id
FROM telco_customers3
ORDER BY 1;


SELECT
  SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) AS null_customer_id,
  SUM(CASE WHEN purchase_amount IS NULL THEN 1 ELSE 0 END) AS null_purchase_amount,
  SUM(CASE WHEN review_rating IS NULL THEN 1 ELSE 0 END) AS null_review_rating
FROM telco_customers3;

-- Value distribution example (top categories)
SELECT category, COUNT(*) AS cnt
FROM telco_customers3
GROUP BY category
ORDER BY cnt DESC
LIMIT 25;


DROP VIEW IF EXISTS vw_kpis_telco;
CREATE VIEW vw_kpis_telco AS
SELECT
  COUNT(*)::bigint AS total_transactions,
  COUNT(DISTINCT customer_id)::bigint AS unique_customers,
  SUM(purchase_amount)::numeric(18,2) AS total_revenue,
  CASE WHEN COUNT(*) = 0 THEN 0 ELSE AVG(purchase_amount)::numeric(18,2) END AS avg_order_value,
  CASE WHEN COUNT(*) = 0 THEN NULL ELSE AVG(review_rating)::numeric(5,2) END AS avg_review_rating,
  SUM(CASE WHEN COALESCE(discountflag,0) = 1 THEN 1 ELSE 0 END)::bigint AS discounted_orders,
  SUM(CASE WHEN COALESCE(promoflag,0) = 1 THEN 1 ELSE 0 END)::bigint AS promo_orders,
  SUM(CASE WHEN COALESCE(isrepeat,0) = 1 THEN 1 ELSE 0 END)::bigint AS repeat_orders,
  CASE WHEN COUNT(*) = 0 THEN 0 ELSE (SUM(CASE WHEN COALESCE(isrepeat,0)=1 THEN 1 ELSE 0 END)::numeric / COUNT(*) ) END AS repeat_order_rate
FROM telco_customers3;

DROP VIEW IF EXISTS vw_revenue_by_location_category_segment;
CREATE VIEW vw_revenue_by_location_category_segment AS
SELECT
  COALESCE(location,'Unknown') AS location,
  COALESCE(category,'Unknown') AS category,
  COALESCE(segment::text,'Unknown') AS segment,
  COUNT(*)::bigint AS customers_count,
  SUM(purchase_amount)::numeric(18,2) AS total_spend,
  AVG(purchase_amount)::numeric(18,2) AS avg_spend,
  AVG(review_rating)::numeric(6,2) AS avg_rating,
  SUM(COALESCE(previous_purchases,0))::bigint AS total_previous_purchases,
  AVG(COALESCE(freqpermonth,0))::numeric(8,2) AS avg_freq_per_month,
  SUM(CASE WHEN COALESCE(isrepeat,0)=1 THEN 1 ELSE 0 END)::bigint AS repeat_customers
FROM telco_customers3
GROUP BY 1,2,3
ORDER BY total_spend DESC;

DROP VIEW IF EXISTS vw_top_items;
CREATE VIEW vw_top_items AS
SELECT
  COALESCE(item_purchased,'Unknown') AS item_purchased,
  COALESCE(category,'Unknown') AS category,
  COUNT(*)::bigint AS sold_count,
  SUM(purchase_amount)::numeric(18,2) AS revenue
FROM telco_customers3
GROUP BY 1,2
ORDER BY revenue DESC;


DROP VIEW IF EXISTS vw_payment_distribution;
CREATE VIEW vw_payment_distribution AS
SELECT
  COALESCE(payment_method,'Unknown') AS payment_method,
  COUNT(*)::bigint AS cnt,
  SUM(purchase_amount)::numeric(18,2) AS revenue
FROM telco_customers3
GROUP BY 1
ORDER BY cnt DESC;

-- Example view for Top N within a chosen category 
DROP VIEW IF EXISTS vw_top_items_by_category;
CREATE VIEW vw_top_items_by_category AS
SELECT
  COALESCE(category,'Unknown') AS category,
  COALESCE(item_purchased,'Unknown') AS item_purchased,
  COUNT(*)::bigint AS sold_count,
  SUM(purchase_amount)::numeric(18,2) AS revenue
FROM telco_customers3
GROUP BY 1,2
ORDER BY revenue DESC;

-- 5) Materialized view for heavy aggregations 
DROP MATERIALIZED VIEW IF EXISTS mv_revenue_by_location;
CREATE MATERIALIZED VIEW mv_revenue_by_location AS
SELECT
  COALESCE(location,'Unknown') AS location,
  SUM(purchase_amount)::numeric(18,2) AS total_revenue,
  COUNT(*)::bigint AS tx_count
FROM telco_customers3
GROUP BY 1;

ANALYZE telco_customers3;

-- Total revenue by location
SELECT location, SUM(purchase_amount)::numeric(18,2) AS total_revenue, COUNT(*) AS tx_count
FROM telco_customers3
GROUP BY location
ORDER BY total_revenue DESC;

-- Average rating and avg spend by category
SELECT category, AVG(review_rating)::numeric(6,2) AS avg_rating, AVG(purchase_amount)::numeric(18,2) AS avg_spend, COUNT(*) AS tx_count
FROM telco_customers3
GROUP BY category
ORDER BY avg_spend DESC;

-- Cohort-like breakdown by segment
SELECT segment, COUNT(*) AS customers_count, SUM(purchase_amount)::numeric(18,2) AS revenue, AVG(freqpermonth)::numeric(8,2) AS avg_freq
FROM telco_customers3
GROUP BY segment
ORDER BY segment;


SELECT customer_id, COUNT(*) FROM telco_customers3 GROUP BY customer_id HAVING COUNT(*)>1 ORDER BY 2 DESC LIMIT 20;

SELECT MIN(purchase_amount) AS min_amt, MAX(purchase_amount) AS max_amt, AVG(purchase_amount)::numeric(18,2) AS avg_amt FROM telco_customers3;

